[2023-09-15T20:18:13.290+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.send_email manual__2023-09-15T20:17:56.330282+00:00 [queued]>
[2023-09-15T20:18:13.301+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.send_email manual__2023-09-15T20:17:56.330282+00:00 [queued]>
[2023-09-15T20:18:13.301+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-15T20:18:13.301+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-09-15T20:18:13.302+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-15T20:18:13.318+0000] {taskinstance.py:1300} INFO - Executing <Task(EmailOperator): send_email> on 2023-09-15 20:17:56.330282+00:00
[2023-09-15T20:18:13.322+0000] {standard_task_runner.py:55} INFO - Started process 1965 to run task
[2023-09-15T20:18:13.325+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_teste', 'send_email', 'manual__2023-09-15T20:17:56.330282+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpgofg949r']
[2023-09-15T20:18:13.325+0000] {standard_task_runner.py:83} INFO - Job 100: Subtask send_email
[2023-09-15T20:18:13.383+0000] {task_command.py:388} INFO - Running <TaskInstance: email_teste.send_email manual__2023-09-15T20:17:56.330282+00:00 [running]> on host 39c967e5fb3d
[2023-09-15T20:18:13.461+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=danilodias_lc@hotmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_teste
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2023-09-15T20:17:56.330282+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-15T20:17:56.330282+00:00
[2023-09-15T20:18:13.507+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-09-15T20:18:13.507+0000] {configuration.py:663} WARNING - section/key [smtp/smtp_user] not found in config
[2023-09-15T20:18:13.508+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-09-15T20:18:13.508+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-09-15T20:18:13.517+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_teste, task_id=send_email, execution_date=20230915T201756, start_date=20230915T201813, end_date=20230915T201813
[2023-09-15T20:18:13.533+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 100 for task send_email ([Errno 99] Cannot assign requested address; 1965)
[2023-09-15T20:18:13.577+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-15T20:18:13.597+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
