[2023-09-15T20:06:15.741+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:06:09.801058+00:00 [queued]>
[2023-09-15T20:06:15.755+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:06:09.801058+00:00 [queued]>
[2023-09-15T20:06:15.756+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-15T20:06:15.756+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-09-15T20:06:15.756+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-15T20:06:15.776+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2023-09-15 20:06:09.801058+00:00
[2023-09-15T20:06:15.781+0000] {standard_task_runner.py:55} INFO - Started process 1089 to run task
[2023-09-15T20:06:15.784+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_teste', 'tsk4', 'manual__2023-09-15T20:06:09.801058+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmp421_7phe']
[2023-09-15T20:06:15.785+0000] {standard_task_runner.py:83} INFO - Job 84: Subtask tsk4
[2023-09-15T20:06:15.855+0000] {task_command.py:388} INFO - Running <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:06:09.801058+00:00 [running]> on host 39c967e5fb3d
[2023-09-15T20:06:15.957+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=danilodias_lc@hotmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_teste
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2023-09-15T20:06:09.801058+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-15T20:06:09.801058+00:00
[2023-09-15T20:06:15.960+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-15T20:06:15.961+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-15T20:06:15.974+0000] {subprocess.py:86} INFO - Output:
[2023-09-15T20:06:15.976+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-15T20:06:16.003+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-15T20:06:16.007+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_teste, task_id=tsk4, execution_date=20230915T200609, start_date=20230915T200615, end_date=20230915T200616
[2023-09-15T20:06:16.026+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 84 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 1089)
[2023-09-15T20:06:16.040+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-15T20:06:16.071+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
