[2023-09-15T20:15:54.783+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:15:49.934854+00:00 [queued]>
[2023-09-15T20:15:54.794+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:15:49.934854+00:00 [queued]>
[2023-09-15T20:15:54.794+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-15T20:15:54.794+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-09-15T20:15:54.794+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-15T20:15:54.813+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2023-09-15 20:15:49.934854+00:00
[2023-09-15T20:15:54.817+0000] {standard_task_runner.py:55} INFO - Started process 1771 to run task
[2023-09-15T20:15:54.819+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_teste', 'tsk4', 'manual__2023-09-15T20:15:49.934854+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmp4p6vq9yw']
[2023-09-15T20:15:54.820+0000] {standard_task_runner.py:83} INFO - Job 91: Subtask tsk4
[2023-09-15T20:15:54.880+0000] {task_command.py:388} INFO - Running <TaskInstance: email_teste.tsk4 manual__2023-09-15T20:15:49.934854+00:00 [running]> on host 39c967e5fb3d
[2023-09-15T20:15:54.965+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=danilodias_lc@hotmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_teste
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2023-09-15T20:15:49.934854+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-15T20:15:49.934854+00:00
[2023-09-15T20:15:54.968+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-15T20:15:54.969+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-15T20:15:54.978+0000] {subprocess.py:86} INFO - Output:
[2023-09-15T20:15:54.982+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-15T20:15:54.994+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-15T20:15:54.999+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_teste, task_id=tsk4, execution_date=20230915T201549, start_date=20230915T201554, end_date=20230915T201554
[2023-09-15T20:15:55.024+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 91 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 1771)
[2023-09-15T20:15:55.048+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-15T20:15:55.084+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
